export const news = [
  {
    title: "Team India Wins Thrilling Test Match Against England",
    date: "January 1, 2023",
    image: "https://images.unsplash.com/photo-1556056504-5c7696c4c28d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
  },
  {
    title: "Cricket World Cup: Australia Dominates in Group Stage",
    date: "January 2, 2023",
    image: "https://images.unsplash.com/photo-1559181567-c3190ca9959b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
  },
  {
    title: "New Rising Star Shines in T20 Cricket League",
    date: "January 3, 2023",
    image: "https://images.unsplash.com/photo-1540984156425-aa05ae3d1501?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
  },
  {
    title: "South Africa Announces Squad for Test Series",
    date: "January 4, 2023",
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
  },
  {
    title: "Indian Premier League Auction: Big Buys and Surprises",
    date: "January 5, 2023",
    image: "https://images.unsplash.com/photo-1517649763962-0c623066013b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
  },
  {
    title: "England's Top Bowler Suffers Injury Blow",
    date: "January 6, 2023",
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
  },
  {
    title: "Cricket Legends Share Tips for Young Cricketers",
    date: "January 7, 2023",
    image: "https://images.unsplash.com/photo-1559181567-c3190ca9959b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
  },
  {
    title: "Pakistan Clinches ODI Series Victory",
    date: "January 8, 2023",
    image: "https://images.unsplash.com/photo-1559847844-5315695dadae?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
  },
  {
    title: "Women's Cricket: India vs. Australia Series Ends in Draw",
    date: "January 9, 2023",
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
  },
]

export const stock = [
  {
    company: "S&P",
    high: "2546",
    down: "6%",
  },
  {
    company: "Apple Inc.",
    high: "150.25",
    down: "1.2%",
  },
  {
    company: "Microsoft Corporation",
    high: "305.50",
    down: "0.8%",
  },
  {
    company: "Amazon.com Inc.",
    high: "3250.75",
    down: "2.5%",
  },
  {
    company: "Alphabet Inc. (Google)",
    high: "2800.00",
    down: "0.5%",
  },
  {
    company: "Facebook, Inc.",
    high: "340.20",
    down: "1.8%",
  },
  {
    company: "Tesla, Inc.",
    high: "750.10",
    down: "2.7%",
  },
  {
    company: "Netflix, Inc.",
    high: "580.30",
    down: "1.3%",
  },
  {
    company: "Johnson & Johnson",
    high: "175.40",
    down: "0.2%",
  },
  {
    company: "Visa Inc.",
    high: "220.75",
    down: "1.1%",
  },
  {
    company: "Walmart Inc.",
    high: "140.60",
    down: "0.7%",
  },
  {
    company: "JPMorgan Chase & Co.",
    high: "155.90",
    down: "1.5%",
  },
  {
    company: "Procter & Gamble Co.",
    high: "135.80",
    down: "0.4%",
  },
  {
    company: "Coca-Cola Company",
    high: "55.45",
    down: "0.9%",
  },
  {
    company: "Johnson Controls International",
    high: "75.20",
    down: "0.6%",
  },
]

export const LiveMatch = {
  typeMatches: [
    {
      matchType: "International",
      seriesMatches: [
        {
          seriesAdWrapper: {
            seriesId: 7135,
            seriesName: "Gulf Cricket T20I Championship 2023",
            matches: [
              {
                matchInfo: {
                  matchId: 81354,
                  seriesId: 7135,
                  seriesName: "Gulf Cricket T20I Championship 2023",
                  matchDesc: "3rd Match",
                  matchFormat: "T20",
                  startDate: "1694869200000",
                  endDate: "1694881800000",
                  state: "Toss",
                  status: "Oman opt to bowl",
                  team1: {
                    teamId: 304,
                    teamName: "Oman",
                    teamSName: "OMAN",
                    imageId: 172353,
                  },
                  team2: {
                    teamId: 7,
                    teamName: "United Arab Emirates",
                    teamSName: "UAE",
                    imageId: 172121,
                  },
                  venueInfo: {
                    id: 582,
                    ground: "West End Park International Cricket Stadium",
                    city: "Doha",
                    timezone: "+03:00",
                    latitude: "25.189391",
                    longitude: "51.460211",
                  },
                  seriesStartDt: "1694736000000",
                  seriesEndDt: "1695600000000",
                  isTimeAnnounced: true,
                  stateTitle: "Toss",
                },
              },
            ],
          },
        },
        {
          adDetail: {
            name: "native_matches",
            layout: "native_large",
            position: 1,
          },
        },
      ],
    },
    {
      matchType: "Domestic",
      seriesMatches: [
        {
          seriesAdWrapper: {
            seriesId: 5241,
            seriesName: "England Domestic One-Day Cup 2023",
            matches: [
              {
                matchInfo: {
                  matchId: 68724,
                  seriesId: 5241,
                  seriesName: "England Domestic One-Day Cup 2023",
                  matchDesc: "Final",
                  matchFormat: "ODI",
                  startDate: "1694858400000",
                  endDate: "1694887200000",
                  state: "Innings Break",
                  status: "Innings Break",
                  team1: {
                    teamId: 145,
                    teamName: "Leicestershire",
                    teamSName: "LEIC",
                    imageId: 172212,
                  },
                  team2: {
                    teamId: 153,
                    teamName: "Hampshire",
                    teamSName: "HAM",
                    imageId: 172220,
                  },
                  venueInfo: {
                    id: 18,
                    ground: "Trent Bridge",
                    city: "Nottingham",
                    timezone: "+01:00",
                    latitude: "52.936884",
                    longitude: "-1.132230",
                  },
                  currBatTeamId: 145,
                  seriesStartDt: "1690848000000",
                  seriesEndDt: "1694995200000",
                  isTimeAnnounced: true,
                  stateTitle: "Ings Break",
                },
                matchScore: {
                  team1Score: {
                    inngs1: {
                      inningsId: 1,
                      runs: 267,
                      wickets: 7,
                      overs: 49.6,
                    },
                  },
                },
              },
            ],
          },
        },
        {
          seriesAdWrapper: {
            seriesId: 7107,
            seriesName: "CSA Provincial One-Day Challenge Division Two 2023",
            matches: [
              {
                matchInfo: {
                  matchId: 80948,
                  seriesId: 7107,
                  seriesName: "CSA Provincial One-Day Challenge Division Two 2023",
                  matchDesc: "1st Match",
                  matchFormat: "ODI",
                  startDate: "1694851200000",
                  endDate: "1694880000000",
                  state: "In Progress",
                  status: "South Western Districts need 255 runs to win the match by herself",
                  team1: {
                    teamId: 281,
                    teamName: "Knights",
                    teamSName: "KNG",
                    imageId: 172331,
                  },
                  team2: {
                    teamId: 1768,
                    teamName: "South Western Districts",
                    teamSName: "SWD",
                    imageId: 174284,
                  },
                  venueInfo: {
                    id: 468,
                    ground: "Recreation Ground",
                    city: "Oudtshoorn",
                    timezone: "+02:00",
                    latitude: "22.1970307",
                    longitude: "-33.5934657",
                  },
                  currBatTeamId: 1768,
                  seriesStartDt: "1694822400000",
                  seriesEndDt: "1697932800000",
                  isTimeAnnounced: true,
                  stateTitle: "In Progress",
                },
                matchScore: {
                  team1Score: {
                    inngs1: {
                      inningsId: 1,
                      runs: 312,
                      wickets: 8,
                      overs: 49.6,
                    },
                  },
                  team2Score: {
                    inngs1: {
                      inningsId: 2,
                      runs: 58,
                      wickets: 2,
                      overs: 11.6,
                    },
                  },
                },
              },
              {
                matchInfo: {
                  matchId: 80955,
                  seriesId: 7107,
                  seriesName: "CSA Provincial One-Day Challenge Division Two 2023",
                  matchDesc: "2nd Match",
                  matchFormat: "ODI",
                  startDate: "1694851200000",
                  endDate: "1694880000000",
                  state: "Complete",
                  status: "Border won by 5 wkts",
                  team1: {
                    teamId: 933,
                    teamName: "Eastern Storm",
                    teamSName: "ESTORM",
                    imageId: 248407,
                  },
                  team2: {
                    teamId: 1775,
                    teamName: "Border",
                    teamSName: "BOR",
                    imageId: 174284,
                  },
                  venueInfo: {
                    id: 99,
                    ground: "Buffalo Park",
                    city: "East London",
                    timezone: "+02:00",
                    latitude: "-33.006727",
                    longitude: "27.919465",
                  },
                  currBatTeamId: 1775,
                  seriesStartDt: "1694822400000",
                  seriesEndDt: "1697932800000",
                  isTimeAnnounced: true,
                  stateTitle: "Complete",
                },
                matchScore: {
                  team1Score: {
                    inngs1: {
                      inningsId: 1,
                      runs: 125,
                      wickets: 10,
                      overs: 29.3,
                    },
                  },
                  team2Score: {
                    inngs1: {
                      inningsId: 2,
                      runs: 128,
                      wickets: 5,
                      overs: 30.2,
                    },
                  },
                },
              },
              {
                matchInfo: {
                  matchId: 80957,
                  seriesId: 7107,
                  seriesName: "CSA Provincial One-Day Challenge Division Two 2023",
                  matchDesc: "3rd Match",
                  matchFormat: "ODI",
                  startDate: "1694851200000",
                  endDate: "1694880000000",
                  state: "In Progress",
                  status: "Limpopo need 168 runs",
                  team1: {
                    teamId: 923,
                    teamName: "Northern Cape",
                    teamSName: "NCAPE",
                    imageId: 248438,
                  },
                  team2: {
                    teamId: 912,
                    teamName: "Limpopo",
                    teamSName: "LIMPO",
                    imageId: 248430,
                  },
                  venueInfo: {
                    id: 148,
                    ground: "Diamond Oval",
                    city: "Kimberley",
                    timezone: "+02:00",
                    latitude: "-28.742487",
                    longitude: "24.742101",
                  },
                  currBatTeamId: 912,
                  seriesStartDt: "1694822400000",
                  seriesEndDt: "1697932800000",
                  isTimeAnnounced: true,
                  stateTitle: "In Progress",
                },
                matchScore: {
                  team1Score: {
                    inngs1: {
                      inningsId: 1,
                      runs: 230,
                      wickets: 9,
                      overs: 49.6,
                    },
                  },
                  team2Score: {
                    inngs1: {
                      inningsId: 2,
                      runs: 63,
                      wickets: 2,
                      overs: 19.6,
                    },
                  },
                },
              },
            ],
          },
        },
        {
          seriesAdWrapper: {
            seriesId: 7105,
            seriesName: "CSA Provincial One-Day Challenge Division One 2023",
            matches: [
              {
                matchInfo: {
                  matchId: 80805,
                  seriesId: 7105,
                  seriesName: "CSA Provincial One-Day Challenge Division One 2023",
                  matchDesc: "1st Match",
                  matchFormat: "ODI",
                  startDate: "1694862000000",
                  endDate: "1694890800000",
                  state: "Rain",
                  status: "Rain stops play",
                  team1: {
                    teamId: 1759,
                    teamName: "Boland",
                    teamSName: "BOL",
                    imageId: 174284,
                  },
                  team2: {
                    teamId: 90,
                    teamName: "Dolphins",
                    teamSName: "DOL",
                    imageId: 172183,
                  },
                  venueInfo: {
                    id: 74,
                    ground: "Kingsmead",
                    city: "Durban",
                    timezone: "+02:00",
                    latitude: "-29.850018",
                    longitude: "31.027888",
                  },
                  currBatTeamId: 1759,
                  seriesStartDt: "1694822400000",
                  seriesEndDt: "1698624000000",
                  isTimeAnnounced: true,
                  stateTitle: "Break",
                },
                matchScore: {
                  team1Score: {
                    inngs1: {
                      inningsId: 1,
                      runs: 32,
                      overs: 6.3,
                    },
                  },
                },
              },
              {
                matchInfo: {
                  matchId: 80812,
                  seriesId: 7105,
                  seriesName: "CSA Provincial One-Day Challenge Division One 2023",
                  matchDesc: "2nd Match",
                  matchFormat: "ODI",
                  startDate: "1694862000000",
                  endDate: "1694890800000",
                  state: "In Progress",
                  status: "North West opt to bat",
                  team1: {
                    teamId: 922,
                    teamName: "North West",
                    teamSName: "NWEST",
                    imageId: 248439,
                  },
                  team2: {
                    teamId: 917,
                    teamName: "Western Province",
                    teamSName: "WPR",
                    imageId: 248460,
                  },
                  venueInfo: {
                    id: 102,
                    ground: "Senwes Park",
                    city: "Potchefstroom",
                    timezone: "+02:00",
                    latitude: "-26.695565",
                    longitude: "27.100691",
                  },
                  currBatTeamId: 922,
                  seriesStartDt: "1694822400000",
                  seriesEndDt: "1698624000000",
                  isTimeAnnounced: true,
                  stateTitle: "In Progress",
                },
                matchScore: {
                  team1Score: {
                    inngs1: {
                      inningsId: 1,
                      runs: 157,
                      wickets: 3,
                      overs: 31,
                    },
                  },
                },
              },
            ],
          },
        },
      ],
    },
  ],
  filters: {
    matchType: ["International", "League", "Domestic", "Women"],
  },
  appIndex: {
    seoTitle: "Live Cricket Score - Scorecard and Match Results",
    webURL: "www.cricbuzz.com/live-cricket-scores/",
  },
  responseLastUpdated: "1694870959",
}

export const QuoteResponseJSON = {
  quoteDate: {
    quoteResponse: {
      result: [
        {
          language: "en-IN",
          region: "IN",
          quoteType: "INDEX",
          typeDisp: "Index",
          quoteSourceName: "Delayed Quote",
          triggerable: true,
          customPriceAlertConfidence: "HIGH",
          components: [
            "BAJAJFINSV.NS",
            "HINDALCO.NS",
            "TCS.NS",
            "COALINDIA.NS",
            "NESTLEIND.NS",
            "TATASTEEL.NS",
            "CIPLA.NS",
            "KOTAKBANK.NS",
            "NTPC.NS",
            "BHARTIARTL.NS",
            "APOLLOHOSP.NS",
            "LTIM.NS",
            "TITAN.NS",
            "RELIANCE.NS",
            "ADANIENT.NS",
            "MARUTI.NS",
            "ITC.NS",
            "BAJAJ-AUTO.NS",
            "ULTRACEMCO.NS",
            "INDUSINDBK.NS",
            "MM.NS",
            "BAJFINANCE.NS",
            "ONGC.NS",
            "BRITANNIA.NS",
            "HEROMOTOCO.NS",
            "TATACONSUM.NS",
            "LT.NS",
            "WIPRO.NS",
            "HDFCLIFE.NS",
            "TECHM.NS",
            "ICICIBANK.NS",
            "GRASIM.NS",
            "HCLTECH.NS",
            "EICHERMOT.NS",
            "SBILIFE.NS",
            "SBIN.NS",
            "ASIANPAINT.NS",
            "UPL.NS",
            "POWERGRID.NS",
            "HINDUNILVR.NS",
            "TATAMOTORS.NS",
            "DIVISLAB.NS",
            "BPCL.NS",
            "HDFCBANK.NS",
            "DRREDDY.NS",
            "SUNPHARMA.NS",
            "ADANIPORTS.NS",
            "JSWSTEEL.NS",
            "AXISBANK.NS",
            "INFY.NS",
          ],
          currency: "INR",
          firstTradeDateMilliseconds: 1190000700000,
          priceHint: 2,
          regularMarketChange: -82,
          regularMarketChangePercent: -0.41996256,
          regularMarketTime: 1699869718,
          regularMarketPrice: 19443.55,
          regularMarketDayHigh: 19494.4,
          regularMarketDayRange: "19414.75 - 19494.4",
          regularMarketDayLow: 19414.75,
          regularMarketVolume: 0,
          regularMarketPreviousClose: 19525.55,
          bid: 0,
          ask: 0,
          bidSize: 0,
          askSize: 0,
          exchange: "NSI",
          market: "in_market",
          messageBoardId: "finmb_INDEXNSEI",
          fullExchangeName: "NSE",
          shortName: "NIFTY 50",
          longName: "NIFTY 50",
          regularMarketOpen: 19486.75,
          averageDailyVolume3Month: 245503,
          averageDailyVolume10Day: 195950,
          fiftyTwoWeekLowChange: 2615.2012,
          fiftyTwoWeekLowChangePercent: 0.1554045,
          fiftyTwoWeekRange: "16828.35 - 20222.45",
          fiftyTwoWeekHighChange: -778.89844,
          fiftyTwoWeekHighChangePercent: -0.038516525,
          fiftyTwoWeekLow: 16828.35,
          fiftyTwoWeekHigh: 20222.45,
          marketState: "CLOSED",
          fiftyDayAverage: 19569.742,
          fiftyDayAverageChange: -126.19141,
          fiftyDayAverageChangePercent: -0.0064482917,
          twoHundredDayAverage: 18684.377,
          twoHundredDayAverageChange: 759.1738,
          twoHundredDayAverageChangePercent: 0.040631477,
          sourceInterval: 15,
          exchangeDataDelayedBy: 15,
          exchangeTimezoneName: "Asia/Kolkata",
          exchangeTimezoneShortName: "IST",
          gmtOffSetMilliseconds: 19800000,
          esgPopulated: false,
          tradeable: false,
          cryptoTradeable: false,
          symbol: "^NSEI",
        },
        {
          language: "en-IN",
          region: "IN",
          quoteType: "INDEX",
          typeDisp: "Index",
          quoteSourceName: "Delayed Quote",
          triggerable: false,
          customPriceAlertConfidence: "LOW",
          components: [
            "500790.BO",
            "500228.BO",
            "532755.BO",
            "507685.BO",
            "500209.BO",
            "500520.BO",
            "500247.BO",
            "500696.BO",
            "500820.BO",
            "532500.BO",
            "532898.BO",
            "500510.BO",
            "532187.BO",
            "500325.BO",
            "532978.BO",
            "532540.BO",
            "500034.BO",
            "532454.BO",
            "532215.BO",
            "500875.BO",
            "532555.BO",
            "500114.BO",
            "500470.BO",
            "500112.BO",
            "532538.BO",
            "500180.BO",
            "532281.BO",
            "524715.BO",
            "532174.BO",
            "500570.BO",
          ],
          currency: "INR",
          firstTradeDateMilliseconds: 867728700000,
          priceHint: 2,
          regularMarketChange: -325.57812,
          regularMarketChangePercent: -0.49889806,
          regularMarketTime: 1699869650,
          regularMarketPrice: 64933.87,
          regularMarketDayHigh: 65176.96,
          regularMarketDayRange: "64853.36 - 65176.96",
          regularMarketDayLow: 64853.36,
          regularMarketVolume: 0,
          regularMarketPreviousClose: 65259.45,
          bid: 0,
          ask: 0,
          bidSize: 0,
          askSize: 0,
          exchange: "BSE",
          market: "in_market",
          messageBoardId: "finmb_INDEXBSESN",
          fullExchangeName: "BSE",
          shortName: "S&P BSE SENSEX",
          longName: "S&P BSE SENSEX",
          regularMarketOpen: 65158.31,
          averageDailyVolume3Month: 11295,
          averageDailyVolume10Day: 9620,
          fiftyTwoWeekLowChange: 7848.961,
          fiftyTwoWeekLowChangePercent: 0.13749625,
          fiftyTwoWeekRange: "57084.91 - 67927.23",
          fiftyTwoWeekHighChange: -2993.3555,
          fiftyTwoWeekHighChangePercent: -0.044067092,
          fiftyTwoWeekLow: 57084.91,
          fiftyTwoWeekHigh: 67927.23,
          marketState: "CLOSED",
          fiftyDayAverage: 65626.99,
          fiftyDayAverageChange: -693.1211,
          fiftyDayAverageChangePercent: -0.010561525,
          twoHundredDayAverage: 63043.953,
          twoHundredDayAverageChange: 1889.918,
          twoHundredDayAverageChangePercent: 0.029977784,
          sourceInterval: 10,
          exchangeDataDelayedBy: 15,
          exchangeTimezoneName: "Asia/Kolkata",
          exchangeTimezoneShortName: "IST",
          gmtOffSetMilliseconds: 19800000,
          esgPopulated: false,
          tradeable: false,
          cryptoTradeable: false,
          symbol: "^BSESN",
        },
        {
          language: "en-IN",
          region: "IN",
          quoteType: "INDEX",
          typeDisp: "Index",
          quoteSourceName: "Delayed Quote",
          triggerable: true,
          customPriceAlertConfidence: "HIGH",
          currency: "INR",
          firstTradeDateMilliseconds: 1190000700000,
          priceHint: 2,
          regularMarketChange: 105.39844,
          regularMarketChangePercent: 0.23956014,
          regularMarketTime: 1699869719,
          regularMarketPrice: 43891.25,
          regularMarketDayHigh: 43970.75,
          regularMarketDayRange: "43681.4 - 43970.75",
          regularMarketDayLow: 43681.4,
          regularMarketVolume: 0,
          regularMarketPreviousClose: 43996.65,
          bid: 0,
          ask: 0,
          bidSize: 0,
          askSize: 0,
          exchange: "NSI",
          market: "in_market",
          messageBoardId: "finmb_INDEXNSEBANK",
          fullExchangeName: "NSE",
          shortName: "NIFTY BANK",
          longName: "NIFTY BANK",
          regularMarketOpen: 43915.1,
          averageDailyVolume3Month: 205909,
          averageDailyVolume10Day: 145140,
          fiftyTwoWeekLowChange: 5278.1016,
          fiftyTwoWeekLowChangePercent: 0.13669182,
          fiftyTwoWeekRange: "38613.15 - 46369.5",
          fiftyTwoWeekHighChange: -2478.25,
          fiftyTwoWeekHighChangePercent: -0.053445693,
          fiftyTwoWeekLow: 38613.15,
          fiftyTwoWeekHigh: 46369.5,
          marketState: "CLOSED",
          fiftyDayAverage: 44232.7,
          fiftyDayAverageChange: -341.44922,
          fiftyDayAverageChangePercent: -0.0077193845,
          twoHundredDayAverage: 43246.355,
          twoHundredDayAverageChange: 644.89453,
          twoHundredDayAverageChangePercent: 0.014912113,
          sourceInterval: 15,
          exchangeDataDelayedBy: 15,
          exchangeTimezoneName: "Asia/Kolkata",
          exchangeTimezoneShortName: "IST",
          gmtOffSetMilliseconds: 19800000,
          esgPopulated: false,
          tradeable: false,
          cryptoTradeable: false,
          symbol: "^NSEBANK",
        },
        {
          language: "en-IN",
          region: "IN",
          quoteType: "INDEX",
          typeDisp: "Index",
          quoteSourceName: "Delayed Quote",
          triggerable: true,
          customPriceAlertConfidence: "HIGH",
          currency: "INR",
          firstTradeDateMilliseconds: 1190000700000,
          priceHint: 2,
          regularMarketChange: -225.15039,
          regularMarketChangePercent: -0.7295629,
          regularMarketTime: 1699869719,
          regularMarketPrice: 30635.85,
          regularMarketDayHigh: 30810.35,
          regularMarketDayRange: "30572.95 - 30810.35",
          regularMarketDayLow: 30572.95,
          regularMarketVolume: 0,
          regularMarketPreviousClose: 30861,
          bid: 0,
          ask: 0,
          bidSize: 0,
          askSize: 0,
          exchange: "NSI",
          market: "in_market",
          messageBoardId: "finmb_INDEXCNXIT",
          fullExchangeName: "NSE",
          shortName: "NIFTY IT",
          longName: "NIFTY IT",
          regularMarketOpen: 30793.65,
          averageDailyVolume3Month: 50565204,
          averageDailyVolume10Day: 11960,
          fiftyTwoWeekLowChange: 4451.4004,
          fiftyTwoWeekLowChangePercent: 0.17000169,
          fiftyTwoWeekRange: "26184.45 - 33402.75",
          fiftyTwoWeekHighChange: -2766.9004,
          fiftyTwoWeekHighChangePercent: -0.08283451,
          fiftyTwoWeekLow: 26184.45,
          fiftyTwoWeekHigh: 33402.75,
          marketState: "CLOSED",
          fiftyDayAverage: 31799.402,
          fiftyDayAverageChange: -1163.5527,
          fiftyDayAverageChangePercent: -0.036590397,
          twoHundredDayAverage: 29988.908,
          twoHundredDayAverageChange: 646.9414,
          twoHundredDayAverageChangePercent: 0.02157269,
          sourceInterval: 15,
          exchangeDataDelayedBy: 15,
          exchangeTimezoneName: "Asia/Kolkata",
          exchangeTimezoneShortName: "IST",
          gmtOffSetMilliseconds: 19800000,
          esgPopulated: false,
          tradeable: false,
          cryptoTradeable: false,
          symbol: "^CNXIT",
        },
        {
          language: "en-IN",
          region: "IN",
          quoteType: "INDEX",
          typeDisp: "Index",
          quoteSourceName: "Delayed Quote",
          triggerable: false,
          customPriceAlertConfidence: "LOW",
          currency: "INR",
          firstTradeDateMilliseconds: 1049168700000,
          priceHint: 2,
          regularMarketChange: 2.0078125,
          regularMarketChangePercent: 0.0051726312,
          regularMarketTime: 1699869659,
          regularMarketPrice: 38814.07,
          regularMarketDayHigh: 38915.76,
          regularMarketDayRange: "38613.06 - 38915.76",
          regularMarketDayLow: 38613.06,
          regularMarketVolume: 0,
          regularMarketPreviousClose: 38816.08,
          bid: 0,
          ask: 0,
          bidSize: 0,
          askSize: 0,
          exchange: "BSE",
          market: "in_market",
          messageBoardId: "finmb_INDEXBSE-SMLCAP.BO",
          fullExchangeName: "BSE",
          shortName: "S&P BSE SMALLCAP INDEX",
          longName: "S&P BSE SMALLCAP INDEX",
          regularMarketOpen: 38915.47,
          averageDailyVolume3Month: 0,
          averageDailyVolume10Day: 0,
          fiftyTwoWeekLowChange: 12693.75,
          fiftyTwoWeekLowChangePercent: 0.48597223,
          fiftyTwoWeekRange: "26120.32 - 38915.76",
          fiftyTwoWeekHighChange: -101.69141,
          fiftyTwoWeekHighChangePercent: -0.002613116,
          fiftyTwoWeekLow: 26120.32,
          fiftyTwoWeekHigh: 38915.76,
          marketState: "CLOSED",
          fiftyDayAverage: 37643.867,
          fiftyDayAverageChange: 1170.2031,
          fiftyDayAverageChangePercent: 0.031086156,
          twoHundredDayAverage: 32334.746,
          twoHundredDayAverageChange: 6479.324,
          twoHundredDayAverageChangePercent: 0.20038271,
          sourceInterval: 10,
          exchangeDataDelayedBy: 15,
          exchangeTimezoneName: "Asia/Kolkata",
          exchangeTimezoneShortName: "IST",
          gmtOffSetMilliseconds: 19800000,
          esgPopulated: false,
          tradeable: false,
          cryptoTradeable: false,
          symbol: "BSE-SMLCAP.BO",
        },
      ],
      error: null,
    },
  },
}
